### ISSUE TITLE
Printing background colors

### ISSUE THREAD

**Issue by arve0** [blob8108/scratchblocks2#70]
I'm unable to print scratchblocks with colors:
![skjermbilde 2015-02-11 kl 07 47 30](https://cloud.githubusercontent.com/assets/4810521/6143097/acc5250e-b1c2-11e4-9b8a-a1a74b48acbe.png)

I've tried:
- ticking *[Print background colors](http://its.yale.edu/how-to/computer-labs-and-printing/article-printing-web-page-background-colors-and-images)* in Safari and Chrome on Mac OS X Yosemite, without luck
- setting the css property on all `div`-fields to `-webkit-print-color-adjust: exact;`
![skjermbilde 2015-02-11 kl 08 00 03](https://cloud.githubusercontent.com/assets/4810521/6143169/30f6ad56-b1c4-11e4-8b6f-c6e70c1b649f.png)

This might be some trouble with my setup, as the background colors for headers are also missing. 

I know it's not a "clean" hack, but will you accept an PR with [this solution](https://defuse.ca/force-print-background.htm)? The image-pixels can easily be created programatically, so that colors can be defined similar to what's in [scratchblocks2.less](https://github.com/blob8108/scratchblocks2/blob/master/src/scratchblocks2.less) now.

Any ideas?

**Comment by blob8108** [comment]
It works on the previous version of Safari:

![screenshot 2015-02-11 10 58 05](https://cloud.githubusercontent.com/assets/639289/6145865/30c1dd3c-b1de-11e4-901c-a5174b43a498.png)

But I do see what you mean about the new one:

![screenshot 2015-02-11 10 57 20](https://cloud.githubusercontent.com/assets/639289/6145868/36428036-b1de-11e4-88c4-47e8740c2f3e.png)

So that's interesting.

Filled backgrounds will waste a lot of ink when printing, anyway. I'm tempted to add a print stylesheet based on the [monochrome fork](https://github.com/blob8108/scratchblocks2/tree/mono):

![screenshot 2014-10-17 15 39 26 copy](https://cloud.githubusercontent.com/assets/639289/6145849/17ad58bc-b1de-11e4-9632-c8cf4ebc2d90.png)

**Comment by arve0** [comment]
@gahjelle

**Comment by blob8108** [comment]
> setting the css property on all div-fields to -webkit-print-color-adjust: exact;

I'm confused as to why this didn't work…

**Comment by arve0** [comment]
My bad! It did work, but bootstrap css was included which had the opposite rule.
